version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  AfterInstall:
   - location: httpd_install.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: httpd_start.sh
     timeout: 300
     runas: root
  ApplicationStop:
   - location: httpd_stop.sh
     timeout: 300
     runas: root
  BeforeInstall:
   - location: httpd_install.sh
     timeout: 300
     runas: root    
